// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFKXYeq48PVRsLy14DmMsStYytcaQ2rE',
    appId: '1:19431857896:web:a53739f70fb96bbddb735d',
    messagingSenderId: '19431857896',
    projectId: 'samplebase-5a9e9',
    authDomain: 'samplebase-5a9e9.firebaseapp.com',
    storageBucket: 'samplebase-5a9e9.firebasestorage.app',
    measurementId: 'G-HJWLC7QCFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu4cPN6g-CaG4vcev85qyM5w__DX0qKpI',
    appId: '1:19431857896:android:9c3c47d06ae6758ddb735d',
    messagingSenderId: '19431857896',
    projectId: 'samplebase-5a9e9',
    storageBucket: 'samplebase-5a9e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOWjqRkeDR9inVmsKX_F5XnS0cfBJtJA',
    appId: '1:19431857896:ios:b8f7bdffad402ec6db735d',
    messagingSenderId: '19431857896',
    projectId: 'samplebase-5a9e9',
    storageBucket: 'samplebase-5a9e9.firebasestorage.app',
    iosBundleId: 'com.arcane.arcane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOWjqRkeDR9inVmsKX_F5XnS0cfBJtJA',
    appId: '1:19431857896:ios:b8f7bdffad402ec6db735d',
    messagingSenderId: '19431857896',
    projectId: 'samplebase-5a9e9',
    storageBucket: 'samplebase-5a9e9.firebasestorage.app',
    iosBundleId: 'com.arcane.arcane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARFKXYeq48PVRsLy14DmMsStYytcaQ2rE',
    appId: '1:19431857896:web:7ce3812333c47912db735d',
    messagingSenderId: '19431857896',
    projectId: 'samplebase-5a9e9',
    authDomain: 'samplebase-5a9e9.firebaseapp.com',
    storageBucket: 'samplebase-5a9e9.firebasestorage.app',
    measurementId: 'G-2PL9NMCQRJ',
  );
}
